backend:
  name: github
  repo: 18f/eca-exchanges-federalist-site
  base_url: https://federalistapp.18f.gov
  auth_endpoint: external/auth/github
  preview_context: federalist/build
  branch: main

media_folder: assets/uploads
public_folder: /images/uploads
publish_mode: editorial_workflow
logo_url: https://federalist.18f.gov/assets/images/federalist-logo.png

collections:
  - label: Programs
    name: programs
    folder: _programs/
    create: true
    slug: "{{slug}}"
    editor:
      preview: true
    fields:
      - {label: 'Layout', name: 'layout', widget: 'hidden', default: 'post'}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Excerpt", name: "excerpt", widget: "string"}
      - {label: "Image", name: "image", widget: "string"}
      - {label: "Image alt text", name: "image-alt-text", widget: "string"}
      - {label: "Location", name: "location", widget: "string"}
      - {label: "Program types", name: "program-types", widget: "list"}
      - {label: "Program length", name: "program-length", widget: "string"}
      - {label: "Dates", name: "dates", widget: "string"}
      - {label: "Cost", name: "cost", widget: "string"}
      - {label: "Visa requirement", name: "visa-requirement", widget: "string"}
      - {label: "Participants", name: "participants", widget: "string"}
      - {label: "Application deadline", name: "application-deadline", widget: "string"}
      - {label: "Eligibility criteria",
         name: "eligibility-criteria",
         widget: "list",
         summary: "{{fields.text}}",
         fields: {
           - label: "Text", name: "text", widget: "string"
         }
        }
      - {label: "", name: "", widget: "string"}
      - {label: "", name: "", widget: "string"}
      - {label: "", name: "", widget: "string"}
      - {label: "", name: "", widget: "string"}
      - {label: "", name: "", widget: "string"}
      - {label: "", name: "", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
